version: '3.8'

services:
  cloudflare:
    image: cloudflare/cloudflared:2023.5.0
    entrypoint: cloudflared --no-autoupdate tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    # network_mode: host
    restart: always

  adguard:
    image: adguard/adguardhome:v0.107.29
    ports:
      - '8089:80/tcp'
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '443:443/tcp'
      - '443:443/udp'
      - '784:784/udp'
      - '853:853/tcp'
      - '853:853/udp'
      - '3001:3000/tcp'
      - '5443:5443/tcp'
      - '5443:5443/udp'
      - '8853:8853/udp'
    volumes:
      - ${USB_MOUNT_POINT}/adguardhome/conf:/opt/adguardhome/conf:rw
      - ${USB_MOUNT_POINT}/adguardhome/work:/opt/adguardhome/work:rw
    # network_mode: host
    restart: always

  ipfs:
    image: ipfs/kubo:master-latest
    ports:
      - '38080:8080'
      - '34001:4001'
    volumes:
      - ${USB_MOUNT_POINT}/ipfs/data:/data/ipfs:rw
      - ${USB_MOUNT_POINT}/ipfs/export:/export:rw
    # network_mode: host
    restart: always

  filebrowser:
    image: filebrowser/filebrowser:v2.23.0
    ports:
      - '8082:80/tcp'
    volumes:
      - ${USB_MOUNT_POINT}/downloads:/srv:rw
      - ${USB_MOUNT_POINT}/filebrowser/config/settings.json:/config/settings.json:rw
      - ${USB_MOUNT_POINT}/filebrowser/database/database.db:/database/database.db:rw
    # network_mode: host
    restart: unless-stopped
