version: '3.9'

networks:
  default:
    driver: bridge

services:
  db:
    container_name: mariadb
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - $SEAFILE_SERVER_VOLUME/mysql:/var/lib/mysql # Requested, specifies the path to MySQL data persistent store.
    restart: always

  memcached:
    container_name: memcached
    image: memcached:1.6.22-alpine
    entrypoint: memcached -m 256
    restart: always

  seafile:
    container_name: seafile
    image: seafileltd/seafile-mc:11.0.2
    ports:
      - $PORT_80:80
      - $PORT_8080:8080
    #     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - $SEAFILE_SERVER_VOLUME/data:/shared # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=$MYSQL_ROOT_PASSWORD # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=America/Argentina/Buenos_Aires # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=$SEAFILE_ADMIN_EMAIL # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=$SEAFILE_ADMIN_PASSWORD # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_HOSTNAME=$SEAFILE_SERVER_HOSTNAME # Specifies your host name if https is enabled.
      - SEAFILE_SERVER_LETSENCRYPT=false # Whether to use https or not.
    depends_on:
      - db
      - memcached
    restart: always
