version: '3.9'

networks:
  default:
    driver: bridge

services:
  db:
    container_name: speedtracker_db
    image: mariadb:11.2.2
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=speedtest_tracker
      - MYSQL_USER=$SPEEDTEST_TRACKER_DB_USERNAME
      - MYSQL_PASSWORD=$SPEEDTEST_TRACKER_DB_PASSWORD
    volumes:
      - $SPEEDTEST_TRACKER_VOLUME/db:/var/lib/mysql
    restart: unless-stopped

  speedtest-tracker:
    container_name: speedtracker
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.13.3
    ports:
      - $PORT_80:80
      - $PORT_443:443
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=$SPEEDTEST_TRACKER_DB_USERNAME
      - DB_PASSWORD=$SPEEDTEST_TRACKER_DB_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SPEEDTEST_TRACKER_VOLUME/config:/config
      - $SPEEDTEST_TRACKER_VOLUME/web:/etc/ssl/web
    restart: unless-stopped
    depends_on:
      - db
