version: '3.9'

networks:
  default:
    driver: bridge

services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.13.3
    ports:
      - $PORT_80:80
      - $PORT_443:443
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $SPEEDTEST_TRACKER_VOLUME/config:/config
      - $SPEEDTEST_TRACKER_VOLUME/web:/etc/ssl/web
    restart: unless-stopped
